
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  php:
    build:
      context: .
      dockerfile: ./php/dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./html:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always