
services:
  nginx:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      dockerfile: ${NGINX_DIR}/Dockerfile
    image: custom-nginx-alpine:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ${WWW_DIR}:/var/www/html
#      - ${NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_DIR}/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - app_network
  php:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      dockerfile: ${PHP_DIR}/Dockerfile
    image: custom-php8.4-alpine:latest
    container_name: php
    volumes:
      - ${WWW_DIR}:/var/www/html
    restart: always
    networks:
      - app_network
  mariadb:
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    image: custom-mariadb-alpine:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 6d520a3373ce552c4fd8cd4ad12e2d36029342daa95f6a84db617953b3f9bcac
      MYSQL_DATABASE: appbase
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: 8a1b4f70831e67c6d675fee7713d58195509f8bedc9fd8d11a
    container_name: mariadb
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    restart: always
    networks:
      - app_network
networks:
  app_network:
    driver: bridge