services:
  nginx:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      dockerfile: ./nginx/Dockerfile
    image: custom-nginx-alpine:latest
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ${WWW}:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - ${NETWORK}
    depends_on:
      - mariadb
      - grafana
      - prometheus

  php:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      dockerfile: ./php/Dockerfile
    image: custom-php8.4-alpine:latest
    container_name: php
    volumes:
      - ${WWW}:/var/www/html
    restart: always
    networks:
      - ${NETWORK}

  mariadb:
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    image: custom-mariadb-alpine:latest
    ports:
      - "3306:3306"
    env_file:
      - ./mariadb/conf/mariadb.env
    container_name: mariadb
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - ${NETWORK}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - ${NETWORK}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - ./grafana/conf/grafana.env
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/conf/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    restart: always
    networks:
      - ${NETWORK}
    depends_on:
      - mariadb

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    command:
      - "--mysqld.username=exporter:0987654321"
      - "--mysqld.address=mariadb:3306"
    ports:
      - "9104:9104"
    restart: always      
    networks:
      - ${NETWORK}
    depends_on:
      - mariadb

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - --nginx.scrape-uri=http://nginx:8080/stub_status
    restart: always
    networks:
      - ${NETWORK}
    depends_on:
      - nginx

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /dev:/dev:ro
      - /run:/run:ro
      - /proc:/proc:ro
    networks:
      - ${NETWORK}
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - ${NETWORK}
    restart: always   

networks:
  app_net:
    driver: bridge