services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - app_network
  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    environment:
      - DATA_SOURCE_NAME=mysqld_exporter:password@(mariadb:3306)/
    ports:
      - "9104:9104"
    networks:
      - app_network








networks:
  app_network:
    driver: bridge