global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']