FROM php:fpm-alpine

#RUN apt-get update && apt-get install -y \
#    libfreetype6-dev \
#    libjpeg62-turbo-dev \
#    libpng-dev \
#    iproute2 \
#    && docker-php-ext-configure gd --with-freetype --with-jpeg \
 ##   && docker-php-ext-install pdo pdo_mysql